### ISSUE TITLE
Update Android TensorFlow classifier

### ISSUE THREAD

**Issue by marcominerva** [jimbobbennett/Xam.Plugins.OnDeviceCustomVision#4]
Hi!

Any chance to update the Android TensorFlow classifier according to these changes?: 

- https://github.com/Azure-Samples/cognitive-services-android-customvision-sample#compatibility
- https://github.com/Azure-Samples/cognitive-services-android-customvision-sample/blob/master/app/src/main/java/demo/tensorflow/org/customvision_sample/MSCognitiveServicesClassifier.java

**Comment by jimbobbennett** [comment]
Done in the latest version - it will look for the relevant transformation layer and only apply the image RGB changes if the layer is not present.
