### ISSUE TITLE
Error: Xam.Plugins.OnDeviceCustomVision.OnImageClassifierException failed to classifiy image check inner exception

### ISSUE THREAD

**Issue by isahhin** [jimbobbennett/Xam.Plugins.OnDeviceCustomVision#6]
I'm faced with given error as
"Xam.Plugins.OnDeviceCustomVision.OnImageClassifierException failed to classifiy image check inner exception for more details --->
Java.Lang.illegalArgumentException: No operation named [Placeholder] in the Graph at ... bla bla bla.

This error occured when calling 
_var classifications = await CrossImageClassifier.Current.ClassifyImage(_file.GetStream());_
 even if I put this 
_AndroidImageClassifier.Current.Init("model.pb", "labels.txt", ModelType.General);_
into the MainActivity.cs which is under the Android.package 

How can I overcome from this error. 
I have converted my keras model.hdf5 to models.pb and place the models.pb and labels.txt to Assets folder.

I need help :(

**Comment by jimbobbennett** [comment]
This plugin is designed to work with models exported from the Azure Custom Vision service (https://customvision.ai). If you've created your own model then it probably won't work - to make it work your models will need to have the same inputs and outputs as those exported from custom vision.
